#!/usr/bin/env python3
"""Build docs/pages/harness-overview.html from scripts/templates/html-page.html.

The template's <head> (Luma tokens, styles, pre-paint theme script) and its closing
toggle script are kept verbatim; only the body between <main> and the footer changes.
Every figure and inventory table is recomputed from the repository on each run.

Usage: python3 scripts/pages/make-harness-overview.py
       scripts/validate-html-page.sh --page docs/pages/harness-overview.html
"""
import base64, os, re, subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
tpl = open(os.path.join(ROOT, "scripts/templates/html-page.html")).read()

TITLE = "OhMyOrch Harness — Overview and Status"
SUMMARY = ("How the harness turns a SPECS.md backlog into delivered, reviewed, and "
           "tested OpenSpec changes, and where the backlog stands today.")

head = tpl[: tpl.index("<body>")]
head = head.replace("{{TITLE}}", TITLE).replace("{{SUMMARY}}", SUMMARY)
# Drop the template's authoring comment: it describes the template, not this page.
c0 = head.index("<!--"); c1 = head.index("-->", c0) + 3
head = head[:c0] + "<!-- Generated by /ohmyorch-generate-html-page (US-14.1). Figures: see section#sources. -->" + head[c1:]
tail = tpl[tpl.index("<script>\n  /* Theme toggle"):]

def sh(cmd):
    return subprocess.run(cmd, shell=True, cwd=ROOT, capture_output=True, text=True).stdout.strip()

epics = int(sh("grep -cE '^# EPIC-[0-9]+:' SPECS.md"))
stories = int(sh(r"grep -cE '^### US-[0-9]+\.[0-9]+:' SPECS.md"))
done = int(sh("grep -c '^Status: DONE' SPECS.md"))
inprog = int(sh("grep -c '^Status: IN PROGRESS' SPECS.md || true") or 0)
archived = int(sh("ls openspec/changes/archive | wc -l"))
caps = int(sh("ls openspec/specs | wc -l"))
agents = int(sh("ls .claude/agents/*.md | grep -vc README"))
skills = int(sh("ls .claude/skills | wc -l"))
rules = int(sh("ls .claude/rules/*.md | grep -vc README"))
date = sh("date +%Y-%m-%d")
with open(os.path.join(ROOT, "docs/images/OhMyOrch.png"), "rb") as fh:
    logo = "data:image/png;base64," + base64.b64encode(fh.read()).decode("ascii")
pct = round(100 * done / stories) if stories else 0

epic_rows = []
for e in range(1, epics + 1):
    t = sh(f"grep -E '^# EPIC-{e}:' SPECS.md | sed 's/^# EPIC-[0-9]*: //'")
    awk = ("awk -v e=EPIC-%d '/^# EPIC-/{c=$2; sub(/:$/,\"\",c)} /^### US-/{if(c==e)n++} "
           "/^Status: DONE/{if(c==e)d++} END{print n+0, d+0}' SPECS.md") % e
    n, d = map(int, sh(awk).split())
    badge = ('<span class="badge badge-success">DONE</span>' if n == d
             else '<span class="badge badge-primary">IN PROGRESS</span>')
    epic_rows.append(f'          <tr><td>EPIC-{e}</td><td>{t}</td><td class="num">{d} / {n}</td><td>{badge}</td></tr>')

suites = []
for s in ["write-scope", "guards", "status", "completion", "delivery", "html-page", "harness-reset"]:
    if not os.path.exists(os.path.join(ROOT, f"scripts/test-{s}.sh")):
        continue
    out = sh(f"scripts/test-{s}.sh 2>&1 | sed -n 's/^  passed: //p;s/^  failed: /F/p'")
    parts = out.split()
    p = parts[0] if parts else "unknown"
    f = parts[1][1:] if len(parts) > 1 else "unknown"
    badge = ('<span class="badge badge-success">PASS</span>' if f == "0"
             else '<span class="badge badge-danger">FAIL</span>')
    suites.append((s, p, f, badge))
total = sum(int(p) for _, p, _, _ in suites if p.isdigit())
suite_rows = "\n".join(
    f'          <tr><td><code>scripts/test-{s}.sh</code></td><td class="num">{p}</td><td class="num">{f}</td><td>{b}</td></tr>'
    for s, p, f, b in suites)

import html as _html, json as _json
E = _html.escape

def front(path, key):
    return sh("awk '/^---/{n++; next} n==1' " + path + " | sed -n 's/^" + key + ": //p' | head -1")

# ---- Harness inventory (from .claude/ and scripts/) -------------------------
n_cmds = int(sh("ls .claude/commands/ohmyorch/opsx/*.md | wc -l"))
n_hooks = int(sh("python3 -c \"import json;d=json.load(open('.claude/settings.json'));print(sum(len(h['hooks']) for a in d['hooks'].values() for h in a))\""))
n_agent_hooks = int(sh("grep -l -E 'check-write-scope.sh[^a-z]*--role' .claude/agents/*.md | grep -v README | wc -l"))
n_guards = int(sh("ls scripts/guard-*.sh | wc -l")) + 1
n_validators = int(sh("ls scripts/validate-*.sh | wc -l"))
n_suites = int(sh("ls scripts/test-*.sh | wc -l"))
n_skills_os = int(sh("ls -d .claude/skills/ohmyorch-openspec-* | wc -l"))
n_skills_h = skills - n_skills_os

AGENTS = [
    ("ohmyorch-codebase-analyst", "Codebase Analyst", "<code>CODEBASE.md</code>, returned to <code>/ohmyorch-analyze-codebase</code>"),
    ("ohmyorch-product-specifier", "Product Specifier", "<code>PRD.md</code>, returned to <code>/ohmyorch-generate-prd</code>"),
    ("ohmyorch-spec-ingestor", "Spec Ingestor", "<code>SPECS.md</code>, returned to <code>/ohmyorch-ingest-spec</code>"),
    ("ohmyorch-product-manager", "Product Manager", "selection, <code>status.md</code>, archive, story status"),
    ("ohmyorch-planner", "Planner", "<code>implementation-plan.md</code>, returned to <code>/ohmyorch-plan-feature</code>"),
    ("ohmyorch-implementer", "Implementer", "product code, its tests, <code>tasks.md</code> ticks"),
    ("ohmyorch-reviewer", "Reviewer", "<code>review.md</code> only"),
    ("ohmyorch-tester", "Tester", "<code>test-report.md</code> only"),
]
agent_rows = []
for a, role, prod in AGENTS:
    tools = front(f".claude/agents/{a}.md", "tools")
    hook = sh(f"grep -o -E 'check-write-scope.sh[^a-z]*--role [a-z-]+' .claude/agents/{a}.md | head -1 | sed 's/[\\\\\"]//g'")
    hook_cell = f"<code>{E(hook)}</code>" if hook else "—"
    agent_rows.append(f'          <tr><td><code>{a}</code></td><td>{role}</td><td>{E(tools)}</td><td>{prod}</td><td>{hook_cell}</td></tr>')

SKILLS = [
    ("ohmyorch-analyze-codebase", "map an existing repository"),
    ("ohmyorch-generate-prd", "product sources → product intent"),
    ("ohmyorch-ingest-spec", "intent → epics, stories, Gherkin criteria"),
    ("ohmyorch-product-iteration", "move one story through the gates, step by step"),
    ("ohmyorch-deliver", "drive an epic, story, or task to completion as a loop"),
    ("ohmyorch-plan-feature", "the Planner handoff for one change"),
    ("ohmyorch-review-feature", "independent review of one change"),
    ("ohmyorch-test-feature", "independent acceptance of one change"),
    ("ohmyorch-generate-html-page", "a themed, self-contained explainer or status page"),
    ("ohmyorch-harness-reset", "back up, then restore the canonical empty harness"),
]
ORDER = ["ohmyorch-codebase-analyst", "ohmyorch-product-specifier", "ohmyorch-spec-ingestor", "ohmyorch-product-manager",
         "ohmyorch-planner", "ohmyorch-implementer", "ohmyorch-reviewer", "ohmyorch-tester"]
skill_rows = []
for s, purpose in SKILLS:
    f = f".claude/skills/{s}/SKILL.md"
    arg = front(f, "argument-hint")
    mentioned = set(sh(f"grep -o -E '\\b({'|'.join(ORDER)})\\b' {f} | sort -u").split())
    dele = ", ".join(f"<code>{a}</code>" for a in ORDER if a in mentioned) or "—"
    scr = sh(f"grep -o -E 'scripts/[a-z-]+\\.(sh|js)' {f} | sort -u | sed 's#scripts/##'").split()
    scr_cell = " ".join(f"<code>{x}</code>" for x in scr) or "—"
    inv = f"<code>/{s}{(' ' + E(arg)) if arg else ''}</code>"
    skill_rows.append(f'          <tr><td>{inv}</td><td>{purpose}</td><td>{dele}</td><td>{scr_cell}</td></tr>')

CMD_PURPOSE = {
    "explore": "think through the problem and the repository; no implementation",
    "propose": "create the change: proposal, delta specs, design, tasks",
    "apply": "implement the change's tasks",
    "verify": "check the implementation against the change's specs (advisory)",
    "sync": "merge delta specs into the canonical specs",
    "archive": "archive the change and sync its specs",
    "update": "revise a change's planning artifacts coherently",
}
cmd_rows = []
for c in sh("ls .claude/commands/ohmyorch/opsx | sed 's/\\.md$//'").split():
    cmd_rows.append(f'          <tr><td><code>/ohmyorch:opsx:{c}</code></td><td><code>ohmyorch-openspec-{"apply-change" if c=="apply" else c + ("-change" if c in ("archive","verify","update") else ("-specs" if c=="sync" else ""))}</code></td><td>{CMD_PURPOSE.get(c, "—")}</td></tr>')

RULES = [
    ("ohmyorch-codebase-context.md", "<code>CODEBASE.md</code> is evidence, never intent; read it before any PRD or SPECS write", "<code>guard-context-preflight.sh</code>, <code>validate-product-artifacts.sh</code>"),
    ("ohmyorch-delivery-loop.md", "a goal is a target delivered story by story; the next action is derived; when the loop may stop", "<code>guard-delivery-loop.sh</code>, <code>delivery.sh</code>"),
    ("ohmyorch-gherkin.md", "every criterion has Given, When, Then; MUST / SHOULD / MAY are literal", "<code>validate-product-artifacts.sh</code> (READY stories)"),
    ("ohmyorch-openspec.md", "the change lifecycle, durable state, archival, the status vocabulary", "<code>guard-archive.sh</code>, <code>guard-story-done.sh</code>, <code>workflow-status.sh</code>"),
    ("ohmyorch-specification-ingestion.md", "no invented behavior; bounded, testable READY stories", "<code>validate-product-artifacts.sh</code>"),
    ("ohmyorch-team-responsibilities.md", "the eight roles and the three no-self-approval prohibitions", "<code>check-write-scope.sh</code>"),
    ("ohmyorch-testing.md", "Tester independence; UNVERIFIED is never PASS", "<code>validate-test-report.sh</code>"),
]
rule_rows = "\n".join(f'          <tr><td><code>{r}</code></td><td>{g}</td><td>{e}</td></tr>' for r, g, e in RULES)

BLOCKS = {
    "guard-planning-handoff.sh": "a product-code write before <code>implementation-plan.md</code> exists",
    "guard-context-preflight.sh": "a PRD or SPECS write without current <code>CODEBASE.md</code> context",
    "guard-story-done.sh": "<code>Status: DONE</code> before the change is archived",
    "guard-delivery-loop.sh": "",
    "guard-archive.sh": "<code>openspec archive</code> while a completion condition fails",
    "validate-product-artifacts.sh": "reports a malformed product artifact after the write",
    "run-project-validation.sh": "runs the project's fast validation after the write",
}
hook_rows = []
settings = _json.load(open(os.path.join(ROOT, ".claude/settings.json")))
for ev, arr in settings["hooks"].items():
    for h in arr:
        for x in h["hooks"]:
            m = re.search(r"scripts/([a-z-]+\.sh)", x["command"])
            scr = m.group(1) if m else "?"
            what = BLOCKS.get(scr, "")
            if scr == "guard-delivery-loop.sh":
                what = ("ending the turn while an ACTIVE goal has work left" if ev == "Stop"
                        else "a main-session write to <code>review.md</code> / <code>test-report.md</code> while a goal is ACTIVE")
            hook_rows.append(f'          <tr><td><code>{ev}</code></td><td><code>{E(h.get("matcher", "—") or "—")}</code></td><td><code>{scr}</code></td><td><code>.claude/settings.json</code></td><td>{what}</td></tr>')
for a in ["ohmyorch-implementer", "ohmyorch-reviewer", "ohmyorch-tester"]:
    hook_rows.append(f'          <tr><td><code>PreToolUse</code></td><td><code>Write|Edit|MultiEdit</code></td><td><code>check-write-scope.sh --role {a}</code></td><td><code>.claude/agents/{a}.md</code></td><td>a {a} write outside its scope</td></tr>')

# ---- EPIC-12, from the archive ---------------------------------------------
e12_rows = []
for d in sorted(sh("ls -d openspec/changes/archive/*us-12-*").split()):
    name = os.path.basename(d)
    story = "US-" + re.search(r"us-(\d+)-(\d+)", name).group(1) + "." + re.search(r"us-(\d+)-(\d+)", name).group(2)
    ntask = sh(f"grep -c '^- \\[x\\]' {d}/tasks.md")
    rounds = 1 + int(sh(f"ls {d}/history 2>/dev/null | grep -c review || true") or 0)
    cov = sh(f"sed -n 's/^Coverage: \\([0-9]*\\/[0-9]*\\).*/\\1/p' {d}/test-report.md | head -1")
    verdict = sh(f"sed -n 's/^Verdict: //p' {d}/review.md | head -1")
    capsl = " ".join(f"<code>{c}</code>" for c in sh(f"ls {d}/specs").split())
    e12_rows.append(f'          <tr><td>{story}</td><td><code>{name}</code></td><td class="num">{ntask}</td><td class="num">{rounds}</td><td>{E(verdict)}</td><td class="num">{cov}</td><td>{capsl}</td></tr>')
e12_rows = "\n".join(e12_rows)

S_WORKFLOWS = f'''
  <section id="workflows" data-component="svg-overlay">
    <h2>Getting started: every workflow</h2>
    <p class="section-lead">Where you start depends on two facts: whether the repository already has meaningful code, and whether a <code>PRD.md</code> exists. Every path ends at the same place: a <code>SPECS.md</code> backlog of READY stories.</p>
    <figure class="figure">
      <div class="figure-canvas">
      <svg viewBox="0 0 760 320" role="img" aria-labelledby="wf-title wf-desc">
        <title id="wf-title">From product sources to delivery</title>
        <desc id="wf-desc">Product sources flow to /ohmyorch-analyze-codebase, which runs only for an existing codebase and writes CODEBASE.md. Then /ohmyorch-generate-prd writes PRD.md when there is none, or updates it. Then /ohmyorch-ingest-spec writes SPECS.md. Two ways to deliver follow: /ohmyorch-product-iteration for one story step by step, or /ohmyorch-deliver for a goal loop. Guards check every PRD.md and SPECS.md write for codebase context.</desc>
        <defs>
          <marker id="wf-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" class="svg-arrow"/></marker>
        </defs>
        <rect x="10" y="90" width="115" height="64" rx="10" class="svg-node-muted"/>
        <text x="67" y="116" text-anchor="middle" class="svg-text">product</text>
        <text x="67" y="136" text-anchor="middle" class="svg-text">sources</text>
        <rect x="150" y="90" width="135" height="64" rx="10" class="svg-node"/>
        <text x="217" y="112" text-anchor="middle" class="svg-mono">/ohmyorch-analyze-codebase</text>
        <text x="217" y="130" text-anchor="middle" class="svg-text-sm">brownfield only</text>
        <text x="217" y="145" text-anchor="middle" class="svg-text-sm">→ CODEBASE.md</text>
        <rect x="310" y="90" width="135" height="64" rx="10" class="svg-node"/>
        <text x="377" y="112" text-anchor="middle" class="svg-mono">/ohmyorch-generate-prd</text>
        <text x="377" y="130" text-anchor="middle" class="svg-text-sm">no PRD, or update</text>
        <text x="377" y="145" text-anchor="middle" class="svg-text-sm">→ PRD.md</text>
        <rect x="470" y="90" width="115" height="64" rx="10" class="svg-node"/>
        <text x="527" y="112" text-anchor="middle" class="svg-mono">/ohmyorch-ingest-spec</text>
        <text x="527" y="130" text-anchor="middle" class="svg-text-sm">new or merge</text>
        <text x="527" y="145" text-anchor="middle" class="svg-text-sm">→ SPECS.md</text>
        <rect x="610" y="40" width="140" height="60" rx="10" class="svg-node"/>
        <text x="680" y="66" text-anchor="middle" class="svg-mono">/ohmyorch-product-iteration</text>
        <text x="680" y="84" text-anchor="middle" class="svg-text-sm">one story, by hand</text>
        <rect x="610" y="140" width="140" height="60" rx="10" class="svg-node-primary"/>
        <text x="680" y="166" text-anchor="middle" class="svg-text-on-primary">/ohmyorch-deliver</text>
        <text x="680" y="184" text-anchor="middle" class="svg-text-on-primary">goal loop</text>
        <path d="M125,122 L148,122" class="svg-edge" marker-end="url(#wf-arrow)"/>
        <path d="M285,122 L308,122" class="svg-edge" marker-end="url(#wf-arrow)"/>
        <path d="M445,122 L468,122" class="svg-edge" marker-end="url(#wf-arrow)"/>
        <path d="M585,116 L608,76" class="svg-edge" marker-end="url(#wf-arrow)"/>
        <path d="M585,128 L608,166" class="svg-edge" marker-end="url(#wf-arrow)"/>
        <text x="67" y="178" text-anchor="middle" class="svg-text-sm">none? both skills stop:</text>
        <text x="67" y="194" text-anchor="middle" class="svg-text-sm">never derive from code</text>
        <path d="M217,154 L217,220" class="svg-edge-dash"/>
        <path d="M377,154 L377,220" class="svg-edge-dash"/>
        <path d="M527,154 L527,220" class="svg-edge-dash"/>
        <rect x="150" y="222" width="435" height="90" rx="12" class="svg-zone"/>
        <text x="166" y="242" class="svg-text-sm">on every PRD.md / SPECS.md write: guard-context-preflight.sh</text>
        <text x="166" y="262" class="svg-mono-sm">greenfield             → ALLOW  (Context: absent)</text>
        <text x="166" y="280" class="svg-mono-sm">CODEBASE.md current    → ALLOW  (Context: consumed)</text>
        <text x="166" y="298" class="svg-mono-sm">stale, or code without it → BLOCKED unless recorded</text>
        <circle cx="160" cy="90" r="10" class="svg-pin"/><text x="160" y="94" text-anchor="middle" class="svg-pin-text">1</text>
        <circle cx="437" cy="154" r="10" class="svg-pin"/><text x="437" y="158" text-anchor="middle" class="svg-pin-text">2</text>
        <circle cx="742" cy="200" r="10" class="svg-pin"/><text x="742" y="204" text-anchor="middle" class="svg-pin-text">3</text>
      </svg>
      <details class="overlay-toggle">
        <summary>Explain</summary>
        <div class="overlay-layer">
          <p class="overlay-note" data-side="below" style="--x: 21.05%; --y: 28.13%"><b>1</b>Runs only when the repository has meaningful code. The Codebase Analyst describes what exists and marks unknowns; it never states what to build.</p>
          <p class="overlay-note" data-side="below" style="--x: 57.5%; --y: 48.13%; --note-w: 12rem"><b>2</b>The Product Specifier turns product sources into intent. <code>CODEBASE.md</code> constrains feasibility but is never copied into requirements.</p>
          <p class="overlay-note" data-side="left" style="--x: 97.63%; --y: 62.5%"><b>3</b>From here every workflow is the same: pick a READY story and deliver it as one OpenSpec change, by hand or through the loop.</p>
        </div>
      </details>
      </div>
      <figcaption>The four entry workflows converge on <code>SPECS.md</code>. Select <em>Explain</em> for the role at each numbered step.</figcaption>
    </figure>

    <div class="table-wrap">
      <table>
        <caption>Entry workflows, from README.md §5–§8 and the generate-prd, ingest-spec, and analyze-codebase skills.</caption>
        <thead><tr><th scope="col">Situation</th><th scope="col">Steps</th><th scope="col">Context marker in PRD.md / SPECS.md</th><th scope="col">Guard behavior</th></tr></thead>
        <tbody>
          <tr><td><strong>Greenfield, no PRD</strong><br>no meaningful code</td><td>product sources → <code>/ohmyorch-generate-prd</code> → <code>/ohmyorch-ingest-spec</code> → deliver. Do not run <code>/ohmyorch-analyze-codebase</code>: there is nothing to describe.</td><td><code>CODEBASE Context: absent</code></td><td><span class="badge badge-success">ALLOW</span> no meaningful codebase detected</td></tr>
          <tr><td><strong>Greenfield, PRD exists</strong></td><td><code>/ohmyorch-ingest-spec</code> → deliver. Run <code>/ohmyorch-generate-prd</code> only when product intent changes.</td><td><code>CODEBASE Context: absent</code></td><td><span class="badge badge-success">ALLOW</span></td></tr>
          <tr><td><strong>Brownfield, no PRD</strong><br>code, no product document</td><td><code>/ohmyorch-analyze-codebase</code> → <code>CODEBASE.md</code> → <code>/ohmyorch-generate-prd</code> from product sources, never from the code → <code>/ohmyorch-ingest-spec</code> → deliver.</td><td><code>CODEBASE Context: consumed (&lt;revision&gt;)</code>, or a deliberate <code>skipped (&lt;reason&gt;)</code></td><td><span class="badge badge-danger">BLOCKED</span> when code exists without <code>CODEBASE.md</code> and no skip is recorded</td></tr>
          <tr><td><strong>Brownfield, PRD exists</strong></td><td>refresh <code>CODEBASE.md</code> if HEAD moved → <code>/ohmyorch-generate-prd</code> to update → <code>/ohmyorch-ingest-spec</code> to merge the new source into the backlog → deliver.</td><td><code>consumed (&lt;revision&gt;)</code>, or <code>consumed (&lt;revision&gt;, staleness accepted)</code></td><td><span class="badge badge-danger">BLOCKED</span> when <code>CODEBASE.md</code> describes an older revision</td></tr>
          <tr><td><strong>Backlog already ready</strong><br>SPECS.md has READY stories</td><td>skip straight to <code>/ohmyorch-product-iteration &lt;US-N.M&gt;</code> or <code>/ohmyorch-deliver &lt;target&gt;</code>.</td><td>already recorded</td><td>—</td></tr>
          <tr><td><strong>No product source at all</strong></td><td><code>/ohmyorch-generate-prd</code> and <code>/ohmyorch-ingest-spec</code> stop and report that they need a source.</td><td>—</td><td>existing code is never turned into product intent</td></tr>
        </tbody>
      </table>
    </div>
    <ul class="list">
      <li><strong>Code arrives later.</strong> A greenfield repository that gains code must run <code>/ohmyorch-analyze-codebase</code> before its next PRD or SPECS update; the preflight guard blocks that update until it does.</li>
      <li><strong>Authority order.</strong> A human Product Manager decision, then approved product sources, then the existing <code>PRD.md</code>, then <code>CODEBASE.md</code> as evidence only.</li>
      <li><strong>This repository</strong> is greenfield: <code>PRD.md</code> and <code>SPECS.md</code> both record <code>CODEBASE Context: absent</code>.</li>
    </ul>
  </section>
'''

S_HARNESS = f'''
  <section id="harness" data-component="table">
    <h2>The .claude harness, piece by piece</h2>
    <p class="section-lead">Claude Code reads <code>.claude/</code>: agents, skills, commands, rules, and hook settings. The hooks run the bash scripts in <code>scripts/</code>. Prompts say what an agent should do; hooks and guards decide what it can do.</p>
    <div class="table-wrap">
      <table>
        <caption>Harness building blocks, counted from the repository.</caption>
        <thead><tr><th scope="col">Kind</th><th scope="col">Where</th><th scope="col" class="num">Count</th><th scope="col">What it is</th></tr></thead>
        <tbody>
          <tr><td>Agents</td><td><code>.claude/agents/*.md</code></td><td class="num">{agents}</td><td>one role each: a prompt, a tool allow-list, and optionally a hook. Run as subagents through the <code>Agent</code> tool.</td></tr>
          <tr><td>Skills</td><td><code>.claude/skills/*/SKILL.md</code></td><td class="num">{skills}</td><td>{n_skills_h} harness procedures, invoked as slash commands, plus {n_skills_os} OpenSpec skills generated by the OpenSpec CLI</td></tr>
          <tr><td>Commands</td><td><code>.claude/commands/ohmyorch/opsx/*.md</code></td><td class="num">{n_cmds}</td><td>the <code>/ohmyorch:opsx:*</code> change lifecycle, generated by <code>openspec update</code></td></tr>
          <tr><td>Rules</td><td><code>.claude/rules/*.md</code></td><td class="num">{rules}</td><td>durable contracts that bind every session; each has a guard behind it</td></tr>
          <tr><td>Hooks</td><td><code>.claude/settings.json</code>, agent frontmatter</td><td class="num">{n_hooks} + {n_agent_hooks}</td><td>Claude Code events (<code>PreToolUse</code>, <code>PostToolUse</code>, <code>Stop</code>) wired to scripts</td></tr>
          <tr><td>Guards</td><td><code>scripts/guard-*.sh</code>, <code>check-write-scope.sh</code></td><td class="num">{n_guards}</td><td>scripts that exit <code>2</code> to block a tool call or a stop</td></tr>
          <tr><td>Validators</td><td><code>scripts/validate-*.sh</code></td><td class="num">{n_validators}</td><td>artifact contracts: plan, review, test report, status, completion, product artifacts, HTML pages</td></tr>
          <tr><td>Reporters</td><td><code>workflow-status.sh</code>, <code>completion-gate.sh</code>, <code>status.sh</code>, <code>delivery.sh</code></td><td class="num">4</td><td>derive gate state, archive eligibility, durable state, and the next action</td></tr>
          <tr><td>Suites</td><td><code>scripts/test-*.sh</code></td><td class="num">{n_suites}</td><td>regression suites for the scripts themselves</td></tr>
        </tbody>
      </table>
    </div>

    <h3>Agents</h3>
    <div class="table-wrap">
      <table>
        <caption>Tools and hooks read from each agent's frontmatter. The read-only agents return their artifact; the invoking skill writes it.</caption>
        <thead><tr><th scope="col">Agent</th><th scope="col">Role</th><th scope="col">Claude Code tools</th><th scope="col">Produces</th><th scope="col">Own hook</th></tr></thead>
        <tbody>
{chr(10).join(agent_rows)}
        </tbody>
      </table>
    </div>

    <h3>Skills</h3>
    <div class="table-wrap">
      <table>
        <caption>Harness skills. "Delegates to" and "Scripts" list the agents and scripts each SKILL.md names.</caption>
        <thead><tr><th scope="col">Invoke</th><th scope="col">Purpose</th><th scope="col">Delegates to</th><th scope="col">Scripts</th></tr></thead>
        <tbody>
{chr(10).join(skill_rows)}
        </tbody>
      </table>
    </div>

    <h3>OpenSpec commands</h3>
    <div class="table-wrap">
      <table>
        <caption>Each /opsx command runs its OpenSpec skill, which calls the openspec CLI.</caption>
        <thead><tr><th scope="col">Command</th><th scope="col">Skill</th><th scope="col">Does</th></tr></thead>
        <tbody>
{chr(10).join(cmd_rows)}
        </tbody>
      </table>
    </div>

    <h3>Rules and the guards behind them</h3>
    <div class="table-wrap">
      <table>
        <caption>.claude/rules/: what each rule governs, and what enforces it.</caption>
        <thead><tr><th scope="col">Rule</th><th scope="col">Governs</th><th scope="col">Enforced by</th></tr></thead>
        <tbody>
{rule_rows}
        </tbody>
      </table>
    </div>

    <h3>Hooks</h3>
    <div class="table-wrap">
      <table>
        <caption>Every hook, read from .claude/settings.json and the agents' frontmatter. Each fails open when its script is absent.</caption>
        <thead><tr><th scope="col">Event</th><th scope="col">Matcher</th><th scope="col">Runs</th><th scope="col">Declared in</th><th scope="col">Stops or reports</th></tr></thead>
        <tbody>
{chr(10).join(hook_rows)}
        </tbody>
      </table>
    </div>
  </section>
'''

S_RESET = '''
  <section id="reset" data-component="table">
    <h2>The canonical reset</h2>
    <p class="section-lead"><code>/ohmyorch-harness-reset</code> returns a repository to a blank harness. It backs the scoped artifacts up, verifies that backup, then copies the canonical baseline over them. <code>.claude/</code> is never written: it is the definition of the state being restored.</p>
    <div class="table-wrap">
      <table>
        <caption>Scope from .claude/skills/ohmyorch-harness-reset/manifest.tsv. Application source, docs/pages/, and docs/images/ are outside it.</caption>
        <thead><tr><th scope="col">Path</th><th scope="col">Backed up</th><th scope="col">Reset</th></tr></thead>
        <tbody>
          <tr><td><code>.claude/</code></td><td>yes</td><td><span class="badge badge-success">never</span></td></tr>
          <tr><td><code>CLAUDE.md</code>, including nested copies outside <code>.claude/</code></td><td>yes</td><td>yes</td></tr>
          <tr><td><code>SPEC-LOGS/</code>, <code>openspec/</code>, <code>scripts/</code></td><td>yes</td><td>yes</td></tr>
          <tr><td><code>PRD.md</code>, <code>SPECS.md</code>, <code>README.md</code></td><td>yes</td><td>yes</td></tr>
          <tr><td>anything else, including application source</td><td>no</td><td><span class="badge badge-success">never</span></td></tr>
        </tbody>
      </table>
    </div>
    <h3>How to run it</h3>
    <pre><code>scripts/harness-reset.sh --dry-run   # writes nothing; names the root and the backup path
scripts/harness-reset.sh             # back up, verify, then reset</code></pre>
    <ul class="list">
      <li><strong>Backup first, or nothing changes.</strong> The backup is <code>docs/resets/<yyyy-mm-dd-hh-mm-ss>/</code>. It is verified by SHA-256 manifest before the reset starts. Any backup failure aborts with the tree unchanged.</li>
      <li><strong>An existing backup is not overwritten.</strong> The directory is created with <code>mkdir</code>, not <code>-p</code>, so a collision fails the run.</li>
      <li><strong>Host files survive.</strong> <code>PRESERVE.tsv</code> lists them. <code>scripts/fast-validate.sh</code> is the default, and it is restored from the backup after <code>scripts/</code> is replaced.</li>
      <li><strong>The engine lives under <code>.claude/</code>.</strong> <code>.claude/skills/ohmyorch-harness-reset/harness-reset.sh</code> is what runs. <code>scripts/harness-reset.sh</code> only launches it, because the reset replaces <code>scripts/</code> while bash is still reading the script.</li>
      <li><strong>A reset project is empty, not broken.</strong> It validates. <code>scripts/test-guards.sh</code> expects this repository's delivered backlog, so those navigation cases fail on the virgin <code>SPECS.md</code>. That is the canonical state.</li>
      <li><strong>Do not commit the backup.</strong> It is a byte copy of <code>.claude/</code>, so it contains <code>.claude/settings.local.json</code>. <code>docs/resets/</code> is gitignored for that reason.</li>
    </ul>
    <div class="callout"><p class="callout-title">Restore</p><p><code>cd <root> && cp -RP docs/resets/<timestamp>/. .</code></p></div>
    <p class="section-lead">After a reset, resume from the workflow: <code>/ohmyorch-analyze-codebase</code> when there is source to describe, then <code>/ohmyorch-generate-prd</code>, then <code>/ohmyorch-ingest-spec</code>.</p>
  </section>
'''

S_SENIOR = '''
  <section id="senior" data-component="table">
    <h2>The delivery loop is a senior developer's tooling</h2>
    <p class="section-lead">A senior developer carries a delivery discipline in their head: slice the work, plan before coding, get it reviewed, test against the requirement, never ship with open issues, and ask when the decision is not theirs. The loop turns each habit into a mechanism that runs whether or not anyone remembers it.</p>
    <div class="table-wrap">
      <table>
        <caption>Habit to mechanism, from .claude/skills/ohmyorch-deliver/SKILL.md, .claude/rules/ohmyorch-delivery-loop.md, and scripts/delivery.sh.</caption>
        <thead><tr><th scope="col">The senior habit</th><th scope="col">The loop's mechanism</th></tr></thead>
        <tbody>
          <tr><td>pick the next unblocked piece of work</td><td><code>delivery.sh next</code> walks <code>SPECS.md</code> in order, checking readiness and dependencies, and derives one action</td></tr>
          <tr><td>slice an epic into shippable pieces</td><td>one story = one OpenSpec change; a task delivers its parent story with the task as the <em>Focus</em></td></tr>
          <tr><td>don't start coding without a plan</td><td><code>guard-planning-handoff.sh</code> blocks product-code writes until <code>implementation-plan.md</code> exists</td></tr>
          <tr><td>get a second pair of eyes</td><td>the Reviewer subagent writes <code>review.md</code>; the orchestrator is blocked from writing it</td></tr>
          <tr><td>test against the requirement, not the code</td><td>the Tester subagent scores every Gherkin scenario in <code>test-report.md</code>; UNVERIFIED is never PASS</td></tr>
          <tr><td>fix findings, then re-check</td><td><code>delivery.sh reopen</code> preserves the verdict in <code>history/</code>, appends one task per finding, and re-opens review and test</td></tr>
          <tr><td>never merge with open issues</td><td><code>completion-gate.sh</code> checks four conditions; <code>guard-archive.sh</code> refuses <code>openspec archive</code> until all pass</td></tr>
          <tr><td>don't call it done early</td><td><code>guard-story-done.sh</code> refuses <code>Status: DONE</code> before the archive</td></tr>
          <tr><td>finish what you started</td><td>the <code>Stop</code> hook refuses to end the turn while the goal is ACTIVE and names the next action</td></tr>
          <tr><td>leave a trail</td><td>every artifact stays in the change directory and moves to <code>openspec/changes/archive/</code>; a fresh session resumes from files</td></tr>
          <tr><td>know when to ask</td><td>the <code>escalate</code> action stops the loop and records <code>BLOCKED</code> with the decision needed</td></tr>
        </tbody>
      </table>
    </div>
    <h3>When the loop asks a human</h3>
    <p>The seven escalation causes in <code>scripts/delivery.sh</code>:</p>
    <ol class="steps">
      <li>the story is not READY: a product decision is required;</li>
      <li>the story depends on an unfinished story;</li>
      <li>another change is already active: one at a time;</li>
      <li>the gate reporter could not report;</li>
      <li>an artifact contract fails the acceptance gate;</li>
      <li>every gate passes but a completion condition fails;</li>
      <li>the first incomplete gate is one the loop does not know.</li>
    </ol>
    <div class="callout"><p class="callout-title">The human stays the Product Manager</p><p>The loop does the routine: selection, sequencing, delegation, bookkeeping. People decide scope, answer escalations, and own product intent. A loop that could approve its own work would turn "keep going until done" into "declare done", so it cannot.</p></div>
  </section>
'''

S_STEPS = '''
  <section id="steps" data-component="table">
    <h2>Each step of the loop, and what it invokes</h2>
    <p class="section-lead">One row per action that <code>delivery.sh next</code> can derive. "Hooks" are the ones that fire on that step's tool calls.</p>
    <div class="table-wrap">
      <table>
        <caption>From .claude/skills/ohmyorch-deliver/SKILL.md (Step 2), the agents' frontmatter, and .claude/settings.json.</caption>
        <thead><tr><th scope="col">Action</th><th scope="col">Owner</th><th scope="col">Invoked</th><th scope="col">Scripts</th><th scope="col">Hooks</th><th scope="col">Tools</th><th scope="col">Writes</th></tr></thead>
        <tbody>
          <tr><td><strong>start</strong></td><td>human → Product Manager</td><td><code>/ohmyorch-deliver EPIC-12</code></td><td><code>delivery.sh resolve</code>, <code>start</code></td><td>—</td><td>Bash</td><td><code>openspec/delivery/goal.md</code></td></tr>
          <tr><td><strong>next</strong></td><td>Product Manager</td><td>every turn</td><td><code>delivery.sh next</code> reads <code>SPECS.md</code>, <code>workflow-status.sh</code>, <code>completion-gate.sh</code></td><td>—</td><td>Bash</td><td>nothing: derived</td></tr>
          <tr><td><strong>select</strong></td><td>Product Manager</td><td><code>openspec new change &lt;id&gt;</code></td><td><code>status.sh --change</code></td><td>Pre: <code>guard-context-preflight</code>, <code>guard-story-done</code>; Post: <code>validate-product-artifacts</code></td><td>Bash, Edit</td><td><code>SPECS.md</code> IN PROGRESS + <code>Change:</code>; <code>status.md</code></td></tr>
          <tr><td><strong>propose</strong></td><td>Planner</td><td><code>/ohmyorch:opsx:explore</code>, <code>/ohmyorch:opsx:propose</code></td><td><code>openspec</code> CLI</td><td>Post: validators on each write</td><td>Bash(openspec:*), Write</td><td><code>proposal.md</code>, <code>specs/&lt;capability&gt;/spec.md</code>, <code>design.md</code>, <code>tasks.md</code></td></tr>
          <tr><td><strong>plan</strong></td><td>Planner subagent</td><td><code>/ohmyorch-plan-feature &lt;id&gt;</code> → Agent(<code>ohmyorch-planner</code>)</td><td><code>validate-implementation-plan.sh</code>, <code>workflow-status.sh</code></td><td>Post: validators on the plan write (the planner itself has no Write tool)</td><td>Agent; Read, Grep, Glob, Bash</td><td><code>implementation-plan.md</code></td></tr>
          <tr><td><strong>implement</strong></td><td>Implementer subagent</td><td><code>/ohmyorch:opsx:apply &lt;id&gt;</code> → Agent(<code>ohmyorch-implementer</code>)</td><td><code>check-scope.sh</code>, project tests</td><td>Pre: <code>guard-planning-handoff</code>, <code>check-write-scope --role ohmyorch-implementer</code>; Post: <code>run-project-validation</code></td><td>Read, Grep, Glob, Bash, Write, Edit</td><td>product code, tests, <code>tasks.md</code> ticks</td></tr>
          <tr><td><strong>review</strong></td><td>Reviewer subagent</td><td><code>/ohmyorch-review-feature &lt;id&gt;</code> → Agent(<code>ohmyorch-reviewer</code>), with <code>/ohmyorch:opsx:verify</code></td><td><code>check-scope.sh</code>, <code>validate-review.sh</code>, <code>openspec validate --strict</code></td><td>Pre: <code>check-write-scope --role ohmyorch-reviewer</code>; <code>guard-delivery-loop</code> blocks the main session</td><td>Read, Grep, Glob, Bash, Write, Edit</td><td><code>review.md</code></td></tr>
          <tr><td><strong>reopen</strong></td><td>Product Manager</td><td>after a failing verdict</td><td><code>delivery.sh reopen --change &lt;id&gt;</code></td><td>—</td><td>Bash</td><td><code>history/review-rN.md</code>; <code>RN.k</code> tasks in <code>tasks.md</code></td></tr>
          <tr><td><strong>test</strong></td><td>Tester subagent</td><td><code>/ohmyorch-test-feature &lt;id&gt;</code> → Agent(<code>ohmyorch-tester</code>)</td><td><code>validate-test-report.sh</code></td><td>Pre: <code>check-write-scope --role ohmyorch-tester</code>; <code>guard-delivery-loop</code> blocks the main session</td><td>Read, Grep, Glob, Bash, Write, Edit</td><td><code>test-report.md</code></td></tr>
          <tr><td><strong>archive</strong></td><td>Product Manager</td><td><code>openspec archive &lt;id&gt; -y</code></td><td><code>completion-gate.sh --record</code>, <code>validate-verification.sh</code></td><td>Pre (Bash): <code>guard-archive</code></td><td>Bash</td><td><code>completion.md</code>; <code>openspec/changes/archive/&lt;date&gt;-&lt;id&gt;/</code>; <code>openspec/specs/&lt;capability&gt;/</code></td></tr>
          <tr><td><strong>mark-done</strong></td><td>Product Manager</td><td>edit <code>SPECS.md</code></td><td><code>delivery.sh refresh</code></td><td>Pre: <code>guard-story-done</code>; Post: <code>validate-product-artifacts</code></td><td>Edit, Bash</td><td><code>SPECS.md</code> <code>Status: DONE</code>, archive path</td></tr>
          <tr><td><strong>between steps</strong></td><td>Product Manager</td><td>after every action</td><td><code>status.sh --change &lt;id&gt; --quiet</code>, <code>delivery.sh refresh</code></td><td>Stop: <code>guard-delivery-loop</code> (exit 2 while work remains)</td><td>Bash</td><td><code>status.md</code>, <code>goal.md</code></td></tr>
          <tr><td><strong>escalate</strong> / <strong>complete</strong></td><td>human Product Manager</td><td>the loop stops</td><td><code>delivery.sh block</code> / <code>refresh</code>, called by the Stop hook</td><td>Stop: the hook allows the stop</td><td>—</td><td><code>goal.md</code> BLOCKED or COMPLETE</td></tr>
        </tbody>
      </table>
    </div>
  </section>
'''

# Swimlane for US-12.2 ---------------------------------------------------------
LANES = [("Product Manager", "main session", 70), ("Planner", "subagent · read-only", 130),
         ("Implementer", "main session †", 190), ("Reviewer", "subagent", 250),
         ("Tester", "subagent", 310), ("Hooks", "settings + agents", 370)]
STEPS = [("select", 0), ("propose", 1), ("plan", 1), ("apply", 2), ("review 1", 3),
         ("R1 fixes", 2), ("review 2", 3), ("test", 4), ("archive", 0), ("DONE", 0)]
HOOKS = {0: ("guard-story-done", 366), 3: ("guard-planning-handoff", 366), 4: ("check-write-scope", 384),
         7: ("check-write-scope", 366), 8: ("guard-archive", 384), 9: ("guard-story-done", 366)}
sv = []
for i, (lt, ls, y) in enumerate(LANES):
    cls = "svg-node-muted" if i % 2 == 0 else "svg-node"
    sv.append(f'        <rect x="146" y="{y-25}" width="740" height="50" class="{cls}"/>')
    sv.append(f'        <text x="10" y="{y-3}" class="svg-text">{lt}</text>')
    sv.append(f'        <text x="10" y="{y+13}" class="svg-text-sm">{ls}</text>')
pts = []
for i, (lab, lane) in enumerate(STEPS):
    cx = 180 + 72 * i; y = LANES[lane][2]; pts.append((cx, y))
    sv.append(f'        <rect x="{cx-30}" y="{y-14}" width="60" height="28" rx="7" class="svg-node"/>')
    sv.append(f'        <text x="{cx}" y="{y+4}" text-anchor="middle" class="svg-text-sm" style="fill: var(--foreground)">{lab}</text>')
for i in range(len(pts) - 1):
    (x1, y1), (x2, y2) = pts[i], pts[i + 1]
    sv.append(f'        <path d="M{x1+30},{y1} L{x2-31},{y2}" class="svg-edge" marker-end="url(#sw-arrow)"/>')
for i, (lab, ty) in HOOKS.items():
    cx, y = pts[i]
    sv.append(f'        <path d="M{cx},{y+14} L{cx},{ty-12}" class="svg-edge-dash"/>')
    sv.append(f'        <text x="{cx}" y="{ty}" text-anchor="middle" class="svg-mono-sm">{lab}</text>')
sv.append('        <path d="M146,412 L886,412" class="svg-edge-dash"/>')
sv.append('        <text x="516" y="432" text-anchor="middle" class="svg-text-sm">Stop hook: guard-delivery-loop.sh refuses to end the turn while the goal is ACTIVE, and names the next action</text>')
PINS = [(282, 116), (426, 176), (570, 236), (786, 56), (160, 412)]
for n, (px, py) in enumerate(PINS, 1):
    sv.append(f'        <circle cx="{px}" cy="{py}" r="10" class="svg-pin"/><text x="{px}" y="{py+4}" text-anchor="middle" class="svg-pin-text">{n}</text>')
swim = "\n".join(sv)

S_EXAMPLE = f'''
  <section id="example" data-component="svg-overlay">
    <h2>Worked example: delivering EPIC-12 through Claude</h2>
    <p class="section-lead">EPIC-12 built the delivery loop, and then the loop delivered the rest of the epic. After US-12.1 was archived, the goal was recorded with <code>scripts/delivery.sh start EPIC-12</code>, and every later step followed <code>scripts/delivery.sh next</code> (SPEC-LOGS/README-EPIC-12.md §5). Claude Code 2.1.128, OpenSpec 1.13.2.</p>

    <div class="table-wrap">
      <table>
        <caption>The four EPIC-12 changes, read from their archived artifacts.</caption>
        <thead><tr><th scope="col">Story</th><th scope="col">Archived change</th><th scope="col" class="num">Tasks</th><th scope="col" class="num">Review rounds</th><th scope="col">Final review</th><th scope="col" class="num">Scenarios</th><th scope="col">Capabilities</th></tr></thead>
        <tbody>
{e12_rows}
        </tbody>
      </table>
    </div>

    <h3>One story end to end: US-12.2, "Run the delivery goal loop"</h3>
    <figure class="figure">
      <div class="figure-canvas">
      <svg viewBox="0 0 890 440" role="img" aria-labelledby="sw-title sw-desc">
        <title id="sw-title">US-12.2 delivered across roles</title>
        <desc id="sw-desc">A swimlane with six lanes: Product Manager, Planner, Implementer, Reviewer, Tester, and Hooks. Ten steps run left to right: select, propose, plan, apply, review round 1, R1 fixes, review round 2, test, archive, and DONE. Guards fire at select, apply, review, test, archive, and DONE. The Stop hook spans the whole run.</desc>
        <defs>
          <marker id="sw-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" class="svg-arrow"/></marker>
        </defs>
{swim}
      </svg>
      <details class="overlay-toggle">
        <summary>Explain</summary>
        <div class="overlay-layer">
          <p class="overlay-note" data-side="left" style="--x: 31.69%; --y: 26.36%; --note-w: 12rem"><b>1</b><code>/ohmyorch-plan-feature</code> ran the read-only <code>ohmyorch-planner</code> subagent. Its plan unlocks product-code writes.</p>
          <p class="overlay-note" data-side="below" style="--x: 47.87%; --y: 40%; --note-w: 12rem"><b>2</b>† The implementer subagent cannot write <code>scripts/</code> or <code>.claude/</code>, so the main session implemented EPIC-12.</p>
          <p class="overlay-note" data-side="right" style="--x: 64.04%; --y: 53.64%; --note-w: 12rem"><b>3</b>Round 1 passed with observations; R1.1–R1.4 were fixed and the change was reviewed again.</p>
          <p class="overlay-note" data-side="below" style="--x: 88.31%; --y: 12.73%; --note-w: 11rem"><b>4</b><code>completion-gate.sh</code>: 4/4 conditions; <code>guard-archive.sh</code> allowed the archive.</p>
          <p class="overlay-note" data-side="above" style="--x: 17.98%; --y: 93.64%; --note-w: 13rem"><b>5</b>The Stop hook this story built spans the run. Its live firing was not exercised (README-EPIC-12 §7).</p>
        </div>
      </details>
      </div>
      <figcaption>US-12.2 from selection to DONE. Select <em>Explain</em> for the notes; click anywhere else to close.</figcaption>
    </figure>

    <ol class="steps">
      <li><strong>next → select.</strong> <code>delivery.sh next</code> derived <code>select US-12.2</code>. The Product Manager ran <code>openspec new change us-12-2-run-delivery-goal-loop</code>, set the story <code>IN PROGRESS</code> in <code>SPECS.md</code> (<code>guard-story-done.sh</code> allowed it), and wrote <code>status.md</code> with <code>status.sh</code>.</li>
      <li><strong>propose.</strong> <code>/ohmyorch:opsx:explore</code> then <code>/ohmyorch:opsx:propose</code> produced <code>proposal.md</code>, <code>design.md</code>, <code>specs/delivery-loop/spec.md</code> with six scenarios, and <code>tasks.md</code> with thirteen tasks, each mapped to a scenario.</li>
      <li><strong>plan.</strong> <code>/ohmyorch-plan-feature</code> delegated to the <code>ohmyorch-planner</code> subagent (Read, Grep, Glob, Bash only), which returned <code>implementation-plan.md</code>. <code>validate-implementation-plan.sh</code> passed, and gate 3 (plan-handoff) opened.</li>
      <li><strong>implement.</strong> The main session built <code>.claude/skills/ohmyorch-deliver/SKILL.md</code>, <code>.claude/rules/ohmyorch-delivery-loop.md</code>, <code>scripts/guard-delivery-loop.sh</code> wired as a <code>Stop</code> hook and a <code>PreToolUse</code> verdict guard, and <code>delivery.sh block</code>. It ticked tasks 1.1–2.6. <code>guard-planning-handoff.sh</code> allowed the writes because the plan existed.</li>
      <li><strong>review, round 1.</strong> The <code>ohmyorch-reviewer</code> subagent, limited to <code>review.md</code> by <code>check-write-scope.sh --role ohmyorch-reviewer</code>, passed the change with observations.</li>
      <li><strong>follow-ups.</strong> The verdict was kept as <code>history/review-r1.md</code>, and R1.1–R1.4 were appended and implemented: <code>loop.state</code> cleared on every goal transition, an honest message when a halt cannot be recorded, documented verdict-guard limits, and fixed pluralisation. Code changed, so the change went back to review instead of being archived.</li>
      <li><strong>review, round 2.</strong> Pass, 17/17 tasks, <code>OpenSpec verify: VERIFIED</code>.</li>
      <li><strong>test.</strong> The <code>ohmyorch-tester</code> subagent built its own sandbox (<code>mktemp -d /tmp/tst-us122.XXXXXX</code>) and scored 6/6 scenarios PASS in <code>test-report.md</code>.</li>
      <li><strong>archive.</strong> <code>completion-gate.sh --record</code> wrote <code>completion.md</code> with verdict <code>eligible</code>; <code>openspec archive us-12-2-run-delivery-goal-loop -y</code> passed <code>guard-archive.sh</code> and created <code>openspec/specs/delivery-loop/</code>.</li>
      <li><strong>mark-done, then next.</strong> <code>SPECS.md</code> got <code>Status: DONE</code> and the archive path. <code>delivery.sh refresh</code> recomputed the goal, and <code>next</code> derived <code>select US-12.3</code>. US-12.3 and US-12.4 followed the same steps, and the last <code>next</code> returned <code>complete</code>.</li>
    </ol>

    <h3>What the session sees</h3>
    <pre><code>$ scripts/delivery.sh next
Action:  review
Story:   US-12.2
Change:  us-12-2-run-delivery-goal-loop
Owner:   ohmyorch-reviewer
Command: /ohmyorch-review-feature us-12-2-run-delivery-goal-loop (includes /ohmyorch:opsx:verify)

# if the session tries to end its turn now, the Stop hook answers (exit 2):
Delivery goal EPIC-12 is ACTIVE — do not stop yet.
Next action: review  (owner: ohmyorch-reviewer, story: US-12.2)
Command: /ohmyorch-review-feature us-12-2-run-delivery-goal-loop (includes /ohmyorch:opsx:verify)</code></pre>
    <p class="section-lead">The Stop-hook message is the format documented in <code>.claude/skills/ohmyorch-deliver/SKILL.md</code> Step 3, which uses this step as its example. The whole epic ran as:</p>
    <pre><code>select US-12.2 -&gt; propose -&gt; plan -&gt; implement -&gt; review -&gt; (follow-ups) -&gt; review
-&gt; test -&gt; archive -&gt; mark-done -&gt; select US-12.3 -&gt; propose -&gt; plan -&gt; implement -&gt; ...</code></pre>
    <div class="callout"><p class="callout-title">Known limits, recorded in README-EPIC-12 §7</p><p>Live Claude Code behavior (the hook firing, the 8-block override) was not exercised in a live session. The verdict guard sees only Write, Edit, and MultiEdit, not shell redirects. The main session implemented this harness-on-harness epic, and independence came from delegating planning, review, and testing to separate subagents.</p></div>
  </section>
'''

body = f'''<body>

<header class="header">
  <div class="brand"><img class="brand-logo" src="{logo}" width="1448" height="1086" alt=""><span>OhMyOrch Harness</span></div>
  <button id="theme-toggle" class="toggle" type="button" aria-label="Toggle light and dark theme">
    <span class="icon-moon" aria-hidden="true">☾</span><span class="icon-sun" aria-hidden="true">☀</span>
    <span>Theme</span>
  </button>
</header>

<main class="main">

  <div class="hero">
    <h1>{TITLE}</h1>
    <p class="lead">{SUMMARY}</p>
    <p class="meta">Generated {date} from the working tree (no commits yet) · see <a href="#sources">Sources</a></p>
  </div>

  <nav class="toc" aria-labelledby="toc-title">
    <p class="toc-title" id="toc-title">On this page</p>
    <ol>
      <li><a href="#overview">Overview</a></li>
      <li><a href="#idea">Spec-driven development</a></li>
      <li><a href="#workflows">Getting started: every workflow</a></li>
      <li><a href="#harness">The .claude harness, piece by piece</a></li>
      <li><a href="#roles">The eight roles</a></li>
      <li><a href="#loop">The delivery loop</a></li>
      <li><a href="#senior">A senior developer's tooling</a></li>
      <li><a href="#steps">Each step and what it invokes</a></li>
      <li><a href="#example">Worked example: EPIC-12</a></li>
      <li><a href="#artifacts">Artifacts and handoffs</a></li>
      <li><a href="#enforcement">Hooks and guards</a></li>
      <li><a href="#reset">The canonical reset</a></li>
      <li><a href="#backlog">Backlog status</a></li>
      <li><a href="#suites">Regression suites</a></li>
      <li><a href="#sources">Sources</a></li>
    </ol>
  </nav>

  <section id="overview" data-component="stats">
    <h2>Overview</h2>
    <p class="section-lead">Headline figures, recomputed from the repository when the page was generated.</p>
    <div class="stats">
      <div class="card"><div class="stat-label">Stories delivered</div><div class="stat-value">{done} / {stories}</div><div class="progress" role="progressbar" aria-valuenow="{pct}" aria-valuemin="0" aria-valuemax="100" aria-label="Stories delivered"><span style="width: {pct}%"></span></div></div>
      <div class="card"><div class="stat-label">Epics</div><div class="stat-value">{epics}</div><div class="stat-note">{"all delivered" if inprog == 0 else f"{inprog} {'story' if inprog == 1 else 'stories'} in progress"}</div></div>
      <div class="card"><div class="stat-label">Archived changes</div><div class="stat-value">{archived}</div><div class="stat-note">one per delivered story</div></div>
      <div class="card"><div class="stat-label">Canonical capabilities</div><div class="stat-value">{caps}</div><div class="stat-note">under openspec/specs/</div></div>
      <div class="card"><div class="stat-label">Harness definitions</div><div class="stat-value">{agents + skills}</div><div class="stat-note">{agents} agents + {skills} skills; plus {rules} rules</div></div>
      <div class="card"><div class="stat-label">Suite assertions</div><div class="stat-value">{total}</div><div class="stat-note">across {len(suites)} regression suites</div></div>
    </div>
  </section>

  <section id="idea" data-component="list">
    <h2>Spec-driven development</h2>
    <p class="section-lead">The harness is documentation and configuration: Markdown contracts, agent and skill definitions, and bash scripts that enforce them. There is no application runtime.</p>
    <ul class="list">
      <li><strong>The specification leads.</strong> <code>PRD.md</code> states intent; <code>SPECS.md</code> decomposes it into epics and stories with Gherkin acceptance criteria.</li>
      <li><strong>One story, one change.</strong> Each story becomes its own OpenSpec change under <code>openspec/changes/</code>, never an epic-sized one.</li>
      <li><strong>Files are the state.</strong> Every handoff is a file in the change directory, so a fresh session resumes without chat history.</li>
      <li><strong>Gates are mechanical.</strong> Hooks run scripts that block an action whose preconditions are unmet. A rule that lives only in a prompt can be ignored.</li>
    </ul>
    <div class="callout"><p class="callout-title">Separation of duties</p><p>The Implementer never approves its own work. The Reviewer and the Tester report defects; they do not repair them. A blocked verdict is a successful verdict.</p></div>
  </section>
{S_WORKFLOWS}{S_HARNESS}
  <section id="roles" data-component="table">
    <h2>The eight roles</h2>
    <div class="table-wrap">
      <table>
        <caption>Roles defined in .claude/agents/ and bound by .claude/rules/ohmyorch-team-responsibilities.md.</caption>
        <thead><tr><th scope="col">Role</th><th scope="col">Produces</th><th scope="col">Edits product code?</th></tr></thead>
        <tbody>
          <tr><td>Codebase Analyst</td><td><code>CODEBASE.md</code></td><td>No</td></tr>
          <tr><td>Product Specifier</td><td><code>PRD.md</code></td><td>No</td></tr>
          <tr><td>Spec Ingestor</td><td><code>SPECS.md</code></td><td>No</td></tr>
          <tr><td>Product Manager</td><td>selection, gates, archive, <code>status.md</code></td><td>No</td></tr>
          <tr><td>Planner</td><td><code>implementation-plan.md</code></td><td>No</td></tr>
          <tr><td>Implementer</td><td>product code and its tests</td><td><span class="badge badge-primary">Yes</span></td></tr>
          <tr><td>Reviewer</td><td><code>review.md</code></td><td>No</td></tr>
          <tr><td>Tester</td><td><code>test-report.md</code></td><td>No</td></tr>
        </tbody>
      </table>
    </div>
  </section>

  <section id="loop" data-component="svg-overlay">
    <h2>The delivery loop</h2>
    <p class="section-lead"><code>/ohmyorch-deliver</code> drives one target story by story. The next action is derived by <code>scripts/delivery.sh next</code> on every turn, never remembered.</p>
    <figure class="figure">
      <div class="figure-canvas">
      <svg viewBox="0 0 720 250" role="img" aria-labelledby="loop-title loop-desc">
        <title id="loop-title">The goal-driven delivery loop</title>
        <desc id="loop-desc">Five stages in a row: propose and plan by the Planner, implement by the Implementer, review by the Reviewer, test by the Tester, archive by the Product Manager. A return edge from review and test goes back to implement. After archive, the loop derives the next story.</desc>
        <defs>
          <marker id="loop-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" class="svg-arrow"/></marker>
          <marker id="loop-arrow-p" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" class="svg-arrow-primary"/></marker>
        </defs>
        <rect x="10"  y="90" width="120" height="64" rx="10" class="svg-node"/>
        <text x="70"  y="116" text-anchor="middle" class="svg-text">propose · plan</text>
        <text x="70"  y="136" text-anchor="middle" class="svg-text-sm">Planner</text>
        <rect x="155" y="90" width="120" height="64" rx="10" class="svg-node-primary"/>
        <text x="215" y="116" text-anchor="middle" class="svg-text-on-primary">implement</text>
        <text x="215" y="136" text-anchor="middle" class="svg-text-on-primary">Implementer</text>
        <rect x="300" y="90" width="120" height="64" rx="10" class="svg-node"/>
        <text x="360" y="116" text-anchor="middle" class="svg-text">review</text>
        <text x="360" y="136" text-anchor="middle" class="svg-text-sm">Reviewer</text>
        <rect x="445" y="90" width="120" height="64" rx="10" class="svg-node"/>
        <text x="505" y="116" text-anchor="middle" class="svg-text">test</text>
        <text x="505" y="136" text-anchor="middle" class="svg-text-sm">Tester</text>
        <rect x="590" y="90" width="120" height="64" rx="10" class="svg-node-muted"/>
        <text x="650" y="116" text-anchor="middle" class="svg-text">archive · DONE</text>
        <text x="650" y="136" text-anchor="middle" class="svg-text-sm">Product Manager</text>
        <path d="M130,122 L153,122" class="svg-edge" marker-end="url(#loop-arrow)"/>
        <path d="M275,122 L298,122" class="svg-edge" marker-end="url(#loop-arrow)"/>
        <path d="M420,122 L443,122" class="svg-edge" marker-end="url(#loop-arrow)"/>
        <path d="M565,122 L588,122" class="svg-edge" marker-end="url(#loop-arrow)"/>
        <path d="M430,154 C430,210 215,210 215,156" class="svg-edge-dash" marker-end="url(#loop-arrow)"/>
        <text x="322" y="222" text-anchor="middle" class="svg-text-sm">blocking finding or failed MUST → back to the Implementer</text>
        <path d="M650,90 C650,30 70,30 70,88" class="svg-edge-primary" marker-end="url(#loop-arrow-p)"/>
        <text x="360" y="30" text-anchor="middle" class="svg-text-sm">delivery.sh next derives the next story</text>
        <circle cx="70" cy="78" r="11" class="svg-pin"/><text x="70" y="82" text-anchor="middle" class="svg-pin-text">1</text>
        <circle cx="360" cy="78" r="11" class="svg-pin"/><text x="360" y="82" text-anchor="middle" class="svg-pin-text">2</text>
        <circle cx="650" cy="166" r="11" class="svg-pin"/><text x="650" y="170" text-anchor="middle" class="svg-pin-text">3</text>
      </svg>
      <details class="overlay-toggle">
        <summary>Explain</summary>
        <div class="overlay-layer">
          <p class="overlay-note" data-side="right" style="--x: 9.72%; --y: 31.2%"><b>1</b>Implementation cannot start until <code>implementation-plan.md</code> exists: <code>guard-planning-handoff.sh</code> blocks the write.</p>
          <p class="overlay-note" data-side="right" style="--x: 50%; --y: 31.2%"><b>2</b>Review and test are independent subagents. The orchestrator never writes <code>review.md</code> or <code>test-report.md</code>.</p>
          <p class="overlay-note" data-side="left" style="--x: 90.28%; --y: 66.4%"><b>3</b><code>guard-archive.sh</code> blocks archival until <code>completion-gate.sh</code> passes; only then may the story be marked DONE.</p>
        </div>
      </details>
      </div>
      <figcaption>One story per pass. Select <em>Explain</em> to show the gate that guards each step; click anywhere else to close.</figcaption>
    </figure>
  </section>
{S_SENIOR}{S_STEPS}{S_EXAMPLE}
  <section id="artifacts" data-component="svg-er">
    <h2>Artifacts and handoffs</h2>
    <p class="section-lead">Roles never pass messages. Each writes a file that the next role reads, and a gate checks the file exists and is well formed.</p>
    <figure class="figure">
      <svg viewBox="0 0 720 300" role="img" aria-labelledby="er-title er-desc">
        <title id="er-title">Artifact model: story, change, and change artifacts</title>
        <desc id="er-desc">A SPECS.md story has exactly one OpenSpec change. A change has one proposal, one tasks file, one implementation plan, one review, one test report, and one status record. The review and the test report reference the story's acceptance criteria.</desc>
        <g>
          <rect x="20" y="30" width="200" height="30" rx="8" class="svg-er-head"/>
          <text x="35" y="50" class="svg-text">SPECS.md story</text>
          <rect x="20" y="60" width="200" height="112" class="svg-er-body"/>
          <rect x="32" y="72" width="22" height="14" rx="3" class="svg-badge-pk"/><text x="43" y="82" text-anchor="middle" class="svg-badge-text">PK</text>
          <text x="62" y="83" class="svg-mono">US-N.M</text><text x="208" y="83" text-anchor="end" class="svg-mono-sm">id</text>
          <text x="62" y="111" class="svg-mono">Status</text><text x="208" y="111" text-anchor="end" class="svg-mono-sm">enum</text>
          <text x="62" y="139" class="svg-mono">Acceptance</text><text x="208" y="139" text-anchor="end" class="svg-mono-sm">gherkin</text>
          <text x="62" y="163" class="svg-mono">Change</text><text x="208" y="163" text-anchor="end" class="svg-mono-sm">path</text>
        </g>
        <g>
          <rect x="260" y="30" width="200" height="30" rx="8" class="svg-er-head"/>
          <text x="275" y="50" class="svg-text">OpenSpec change</text>
          <rect x="260" y="60" width="200" height="84" class="svg-er-body"/>
          <rect x="272" y="72" width="22" height="14" rx="3" class="svg-badge-pk"/><text x="283" y="82" text-anchor="middle" class="svg-badge-text">PK</text>
          <text x="302" y="83" class="svg-mono">name</text><text x="448" y="83" text-anchor="end" class="svg-mono-sm">slug</text>
          <rect x="272" y="100" width="22" height="14" rx="3" class="svg-badge-fk"/><text x="283" y="110" text-anchor="middle" class="svg-badge-text">FK</text>
          <text x="302" y="111" class="svg-mono">story</text><text x="448" y="111" text-anchor="end" class="svg-mono-sm">US-N.M</text>
          <text x="302" y="135" class="svg-mono">specs/</text><text x="448" y="135" text-anchor="end" class="svg-mono-sm">delta</text>
        </g>
        <g>
          <rect x="500" y="30" width="200" height="30" rx="8" class="svg-er-head"/>
          <text x="515" y="50" class="svg-text">Change artifact</text>
          <rect x="500" y="60" width="200" height="196" class="svg-er-body"/>
          <rect x="512" y="72" width="22" height="14" rx="3" class="svg-badge-fk"/><text x="523" y="82" text-anchor="middle" class="svg-badge-text">FK</text>
          <text x="542" y="83" class="svg-mono">change</text><text x="688" y="83" text-anchor="end" class="svg-mono-sm">name</text>
          <text x="542" y="111" class="svg-mono">proposal.md</text><text x="688" y="111" text-anchor="end" class="svg-mono-sm">Planner</text>
          <text x="542" y="135" class="svg-mono">tasks.md</text><text x="688" y="135" text-anchor="end" class="svg-mono-sm">Planner</text>
          <text x="542" y="159" class="svg-mono">impl-plan.md</text><text x="688" y="159" text-anchor="end" class="svg-mono-sm">Planner</text>
          <text x="542" y="183" class="svg-mono">review.md</text><text x="688" y="183" text-anchor="end" class="svg-mono-sm">Reviewer</text>
          <text x="542" y="207" class="svg-mono">test-report.md</text><text x="688" y="207" text-anchor="end" class="svg-mono-sm">Tester</text>
          <text x="542" y="231" class="svg-mono">status.md</text><text x="688" y="231" text-anchor="end" class="svg-mono-sm">derived</text>
        </g>
        <path d="M220,107 L260,107" class="svg-edge"/>
        <path d="M230,99 L230,115" class="svg-edge"/>
        <path d="M250,99 L250,115" class="svg-edge"/>
        <text x="240" y="94" text-anchor="middle" class="svg-text-sm">1 — 1</text>
        <path d="M460,97 L500,97" class="svg-edge"/>
        <path d="M470,89 L470,105" class="svg-edge"/>
        <path d="M486,97 L500,89 M486,97 L500,105" class="svg-edge"/>
        <text x="480" y="84" text-anchor="middle" class="svg-text-sm">1 — N</text>
        <text x="240" y="280" text-anchor="middle" class="svg-text-sm">A story is delivered as exactly one change (BR-003).</text>
      </svg>
      <figcaption>The handoff chain. <span class="badge badge-primary">PK</span> identity · <span class="badge badge-success">FK</span> reference to the owner</figcaption>
    </figure>
  </section>

  <section id="enforcement" data-component="svg-infra">
    <h2>Hooks and guards</h2>
    <p class="section-lead">Claude Code runs the hooks declared in <code>.claude/settings.json</code>. Each hook runs a script; a script that exits 2 blocks the tool call or the stop.</p>
    <figure class="figure">
      <svg viewBox="0 0 720 320" role="img" aria-labelledby="infra-title infra-desc">
        <title id="infra-title">Hook infrastructure</title>
        <desc id="infra-desc">A Claude Code session emits PreToolUse, PostToolUse, and Stop events. PreToolUse on writes runs the planning, context, story-done, and delivery-loop guards; PreToolUse on Bash runs the archive guard; PostToolUse runs the artifact validators; Stop runs the delivery-loop guard. Guards read the openspec directory and SPECS.md.</desc>
        <defs>
          <marker id="infra-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" class="svg-arrow"/></marker>
        </defs>
        <rect x="190" y="16" width="310" height="290" rx="14" class="svg-zone"/>
        <text x="206" y="38" class="svg-text-sm">scripts/ — the executable harness</text>
        <rect x="16" y="120" width="140" height="72" rx="10" class="svg-node-primary"/>
        <text x="86" y="148" text-anchor="middle" class="svg-text-on-primary">session</text>
        <text x="86" y="170" text-anchor="middle" class="svg-text-on-primary">Claude Code</text>
        <rect x="214" y="52" width="262" height="72" rx="10" class="svg-node"/>
        <text x="345" y="72" text-anchor="middle" class="svg-text-sm">PreToolUse · Write|Edit|MultiEdit</text>
        <text x="345" y="92" text-anchor="middle" class="svg-mono">guard-planning-handoff · context-preflight</text>
        <text x="345" y="110" text-anchor="middle" class="svg-mono">guard-story-done · delivery-loop</text>
        <rect x="214" y="136" width="262" height="44" rx="10" class="svg-node"/>
        <text x="345" y="154" text-anchor="middle" class="svg-text-sm">PreToolUse · Bash</text>
        <text x="345" y="171" text-anchor="middle" class="svg-mono">guard-archive</text>
        <rect x="214" y="192" width="262" height="52" rx="10" class="svg-node"/>
        <text x="345" y="212" text-anchor="middle" class="svg-text-sm">PostToolUse · Write|Edit|MultiEdit</text>
        <text x="345" y="231" text-anchor="middle" class="svg-mono">validate-product-artifacts · project-validation</text>
        <rect x="214" y="256" width="262" height="40" rx="10" class="svg-node"/>
        <text x="345" y="273" text-anchor="middle" class="svg-text-sm">Stop</text>
        <text x="345" y="289" text-anchor="middle" class="svg-mono">guard-delivery-loop</text>
        <rect x="548" y="80" width="156" height="60" rx="10" class="svg-node-muted"/>
        <text x="626" y="104" text-anchor="middle" class="svg-text-sm">store</text>
        <text x="626" y="124" text-anchor="middle" class="svg-text">openspec/</text>
        <rect x="548" y="190" width="156" height="60" rx="10" class="svg-node-muted"/>
        <text x="626" y="214" text-anchor="middle" class="svg-text-sm">store</text>
        <text x="626" y="234" text-anchor="middle" class="svg-text">SPECS.md</text>
        <path d="M156,140 L212,90" class="svg-edge" marker-end="url(#infra-arrow)"/>
        <path d="M156,156 L212,158" class="svg-edge" marker-end="url(#infra-arrow)"/>
        <path d="M156,170 L212,216" class="svg-edge-dash" marker-end="url(#infra-arrow)"/>
        <path d="M156,184 L212,274" class="svg-edge" marker-end="url(#infra-arrow)"/>
        <text x="170" y="112" class="svg-text-sm">JSON</text>
        <path d="M476,96 L546,108" class="svg-edge" marker-end="url(#infra-arrow)"/>
        <path d="M476,160 L546,124" class="svg-edge" marker-end="url(#infra-arrow)"/>
        <path d="M476,218 L546,220" class="svg-edge" marker-end="url(#infra-arrow)"/>
        <text x="512" y="92" text-anchor="middle" class="svg-text-sm">read</text>
      </svg>
      <figcaption>Hooks as wired in .claude/settings.json. The Implementer, Reviewer, and Tester agents also carry a <code>check-write-scope.sh</code> hook that confines each to its own files.</figcaption>
      <div class="legend">
        <span><i class="swatch" style="background: var(--primary)"></i>event source</span>
        <span><i class="swatch" style="background: var(--muted)"></i>durable state</span>
        <span><svg width="26" height="8" aria-hidden="true"><path d="M0,4 L26,4" class="svg-edge-dash"/></svg>after the tool call</span>
      </div>
    </figure>
    <h3>Exit-code contract</h3>
    <ul class="list">
      <li>Validators: <code>0</code> pass, <code>1</code> fail, <code>2</code> usage error.</li>
      <li>Guards: <code>0</code> allow, <code>2</code> block, <code>3</code> usage error.</li>
      <li>Every hook wrapper fails open when the harness script is absent.</li>
    </ul>
  </section>
{S_RESET}
  <section id="backlog" data-component="table">
    <h2>Backlog status</h2>
    <div class="table-wrap">
      <table>
        <caption>Stories per epic in SPECS.md, counted by status line.</caption>
        <thead><tr><th scope="col">Epic</th><th scope="col">Title</th><th scope="col" class="num">Done</th><th scope="col">Status</th></tr></thead>
        <tbody>
{chr(10).join(epic_rows)}
        </tbody>
      </table>
    </div>
  </section>

  <section id="suites" data-component="table">
    <h2>Regression suites</h2>
    <div class="table-wrap">
      <table>
        <caption>Assertion counts from each suite's summary line.</caption>
        <thead><tr><th scope="col">Suite</th><th scope="col" class="num">Passed</th><th scope="col" class="num">Failed</th><th scope="col">Result</th></tr></thead>
        <tbody>
{suite_rows}
        </tbody>
      </table>
    </div>
  </section>

  <section id="sources" data-component="sources">
    <h2>Sources</h2>
    <p class="section-lead">The files and commands every figure on this page came from, run on {date}. The repository had no commits, so no revision is recorded.</p>
    <ul class="list">
      <li><code>grep -cE '^# EPIC-[0-9]+:' SPECS.md</code> — {epics} epics</li>
      <li><code>grep -cE '^### US-[0-9]+\\.[0-9]+:' SPECS.md</code> — {stories} stories</li>
      <li><code>grep -c '^Status: DONE' SPECS.md</code> — {done} delivered; <code>'^Status: IN PROGRESS'</code> — {inprog}</li>
      <li><code>ls openspec/changes/archive | wc -l</code> — {archived} archived changes</li>
      <li><code>ls openspec/specs | wc -l</code> — {caps} canonical capabilities</li>
      <li><code>ls .claude/agents .claude/skills .claude/rules</code> — {agents} agents, {skills} skills, {rules} rules</li>
      <li><code>scripts/test-&lt;suite&gt;.sh</code> — the passed and failed counts in Regression suites</li>
      <li><code>.claude/settings.json</code> — the hook wiring in Hooks and guards</li>
      <li><code>.claude/rules/ohmyorch-team-responsibilities.md</code>, <code>.claude/rules/ohmyorch-delivery-loop.md</code> — the roles and the loop</li>
      <li><code>CLAUDE.md</code>, <code>PRD.md</code> — the workflow and the separation-of-duties rule</li>
      <li><code>README.md</code> §5–§8, <code>.claude/skills/{{ohmyorch-analyze-codebase,ohmyorch-generate-prd,ohmyorch-ingest-spec}}/SKILL.md</code>, <code>scripts/guard-context-preflight.sh</code> — the entry workflows and their guard outcomes</li>
      <li><code>awk '/^---/{{n++;next}} n==1' .claude/agents/*.md</code> — each agent's tools and hook; <code>grep -o 'scripts/[a-z-]*' .claude/skills/*/SKILL.md</code> — each skill's scripts and delegates</li>
      <li><code>ls .claude/commands/ohmyorch/opsx</code> — {n_cmds} commands; <code>ls scripts/guard-*.sh scripts/validate-*.sh scripts/test-*.sh</code> — guards, validators, suites</li>
      <li><code>.claude/skills/ohmyorch-harness-reset/SKILL.md</code>, <code>manifest.tsv</code>, <code>PRESERVE.tsv</code>, <code>README.md</code> §27 — the canonical reset</li>
      <li><code>docs/images/OhMyOrch.png</code> — the header logo, embedded as a data URI because the page CSP allows only <code>img-src data:</code></li>
      <li><code>.claude/skills/ohmyorch-deliver/SKILL.md</code> Step 2, <code>scripts/delivery.sh</code> (<code>set_action escalate</code>) — the loop steps, owners, and the seven escalation causes</li>
      <li><code>SPEC-LOGS/README-EPIC-12.md</code> — the EPIC-12 narrative, rounds, and known limits</li>
      <li><code>openspec/changes/archive/*us-12-*/</code> (<code>tasks.md</code>, <code>review.md</code>, <code>history/</code>, <code>test-report.md</code>, <code>completion.md</code>, <code>specs/</code>) — the EPIC-12 table and the US-12.2 walkthrough</li>
    </ul>
  </section>

  <footer class="footer">Generated by the harness <code>/ohmyorch-generate-html-page</code> skill · shadcn Luma theme</footer>
</main>

'''

out = os.path.join(ROOT, "docs/pages/harness-overview.html")
os.makedirs(os.path.dirname(out), exist_ok=True)
open(out, "w").write(head + body + tail)
print(out)
